#Holds all of the query information needed for data collection in a dictionary

queries = {
    'Mexico': {'Reddit': ['mexico'],
               'Twitter': ['politica mexico', 'politica mexicana'],
               'Youtube': [{'Title':'Corrupción en México. Presente, pasado y futuro',
                            'Url':'wl321Qxtgg4'},
                           {'Title':'EL PRESIDENTE SE SIENTA A "TRAGAR" ENFRENTE DE LOS POBRES',
                            'Url':'a5VauBLXuJU'},
                           {'Title':'COMO FUNCIONA LA POLITICA EN MEXICO, ASÍ SE ORGANIZAN LOS MAÑOSOS PARA BENEFICIARSE.',
                            'Url':'tqR-2_yz0ZU'},
                           {'Title':'La transición democrática de México: Elecciones del 2000 y Vicente Fox - Bully Magnets - Documental',
                            'Url':'-Aopk9Orr80'},
                           {'Title':'La Democracia en México - Bully Magnets - Historia Documental',
                            'Url':'K1PXDs7U0ew'},
                           {'Title':'La política no me importa -Mientras Tanto en México',
                            'Url':'v7plvmyUbX0'},
                           {'Title':'¿Qué significa Izquierda y Derecha en Política? Una perspectiva desde México',
                            'Url':'mtL5z6nBUr8'},
                           {'Title':'Los ganadores y perdedores de la elección 2021 | Mientras Tanto en México',
                            'Url':'nI3H8hi5fvc'}]
               },
    'Argentina':{'Reddit': ['argentina'],
               'Twitter': ['politica argentina'],
               'Youtube': [{'Title':'La campaña disruptiva de Javier Milei. El fenómeno liberal de la política argentina.',
                            'Url':'_YFkN6_z-aA'},
                           {'Title':'Por qué la política se financia con plata en negro en Argentina | TKM Explica',
                            'Url':'y0C27aDDBJc'},
                           {'Title':'R. Cachanosky "La política en Argentina se transformó en un gran negocio"',
                            'Url':'1BWeAfLuuRM'},
                           {'Title':'"La inflación tiene una sola causa y es el Banco Central" Agustín Etchebarne con Luis Majul',
                            'Url':'ZKU5EdkbAyY'},
                           {'Title':'Javier Milei: “En Argentina hicimos todo mal”',
                            'Url': 'QB8aLCPfYlY'},
                           {'Title': '"El capitalismo sacó a la gente de la pobreza" Javier Milei, mano a mano con Paulino Rodrigues',
                            'Url':'pCx5T-f3vwo'},
                           {'Title':'Exclusivo. Entrevista Mauricio Macri en LN+',
                            'Url':'UUB3FRzFAzI'},
                           {'Title':'Javier Milei: "Alberto Fernández es el peor Presidente de la historia"',
                            'Url':'8B_j8OQ920I'}
                           ]
               },
    'Peru': {'Reddit': ['peru'],
               'Twitter': ['politica peruana', 'politica peru'],
               'Youtube': [{'Title':'El Estado peruano: ¿Qué es y cómo se organiza?',
                            'Url':'JApWatKy5Vo'},
                           {'Title':'PUCP - ¿Cómo funciona la política sin partidos en el Perú? Aula Abierta con Martín Tanaka',
                            'Url':'BxSJroW9KuM'},
                           {'Title':'¿QUIÉN ES RAFAEL LÓPEZ-ALIAGA? (ESPECIAL)',
                            'Url':'S5qXE8oNoRA'},
                           {'Title':'¿QUIÉN ES KEIKO FUJIMORI? (ESPECIAL)',
                            'Url':'RNwjdt2dBbo'},
                           {'Title':'EL FINAL DE DOMINGO PÉREZ (ESPECIAL)',
                            'Url':'cdy7F-yhr0c'},
                           {'Title':'#LaEncerrona ESPECIAL: Los Vladiaudios que no te están mostrando',
                            'Url':'Bels9Z-DJZs'},
                           {'Title':'Debate presidencial en Chota: Propuestas de Keiko Fujimori y Pedro Castillo contra la pandemia',
                            'Url':'jitZpRwFkWY'},
                           {'Title':'Resultados oficiales de la ONPE al 98% : Pedro Castillo 50.24% y Keiko Fujimori 49.75%',
                            'Url':'NkKTX8sSjz0'}]
               },
    'Colombia': {'Reddit': ['colombia'],
               'Twitter': ['politica colombia', 'politica colombiana'],
               'Youtube': [{'Title':'Facebook Live - Análisis de lo que está sucediendo en el país en los últimos días.',
                            'Url':'0M-dpU8WVPk'},
                           {'Title':'#ArielExplica - La clase política colombiana',
                            'Url':'ZyaMn8Y8Nr4'},
                           {'Title':'#ArielExplica - El paramilitarismo en Colombia',
                            'Url': 'P3l44__ZGuI'},
                           {'Title':'La TRAMPA de siempre en la política | La Pulla |',
                            'Url':'k2M6AhuQc8Q'},
                           {'Title':'Así nos ROBAN los políticos en Colombia | La Pulla |',
                            'Url':'By-2sROXgM8'},
                           {'Title':'Aquí empieza la CORRUPCIÓN en Colombia | La Pulla |',
                            'Url':'S-eWGSbVz8s'},
                           {'Title':'¿Usted es de izquierda o derecha?',
                            'Url': 'myqYO7I6MBA'},
                           {'Title':'ESTE ES EL CANDIDATO 😜 POR EL QUE VOTARÉ 💪🏼',
                            'Url':'sERPVE5i4dc'},
                           {'Title':'EL REGUETÓN DE LA CORRUPCIÓN - VIDEO MUSICAL',
                            'Url':'nacvZmMwZuo'}]
               },
    'Chile': {'Reddit': ['chile'],
               'Twitter': ['politica chilena', 'politica chile'],
               'Youtube': [{'Title':'Gloria Álvarez: República Vs Populismo #RepVsPop',
                            'Url':'A6wzSwhhMh0'},
                           {'Title':'Axel Kaiser | La nueva Constitución chilena',
                            'Url': 'uiwDPLX9Vd8'},
                           {'Title':'J. A. Kast vs Diputado FA y Público: "¡Te Puedes Ir Tranquilo!"',
                            'Url':'PU2PlMV42vo'},
                           {'Title':'F. Parisi vs Gabriel Boric: "¿¡Que te Pasa!?"',
                            'Url':'Lxezb-nPl3Y'},
                           {'Title':'José Antonio Kast vs Gabriel Boric: "No quiere Contestar"',
                            'Url':'PnGJOgBpIlQ'},
                           {'Title':'F. Parisi por Viaje Kast a U.S.A: "Lo que hizo Kast fue Brillante"',
                            'Url':'wsk5Qlzr6uU'},
                           {'Title':'Franco Parisi: "Si Sale Boric la Economía Chilena se va a Hundir"',
                            'Url':'JBGw4cDcUnE'},
                           {'Title':'🔴 #DebateCHVCNN: Debate presidencial Primera Vuelta 2021',
                            'Url':'WhXMvrs-5Oc'}]
               },
    'Spain': {'Reddit': ['SpainPolitics'],
               'Twitter': ['politica espanola', 'politica espana'],
               'Youtube': [{'Title':'¡La POLÍTICA ESPAÑOLA ACTUAL, EXPLICADA! ¡EL RESUMEN de la ESTRATEGIA de los PARTIDOS! | Es.Política',
                            'Url':'Wca5hkqdsnk'},
                           {'Title':'TONI CANTÓ se DESCOJONA de IRENE MONTERO y DESMONTA el FEMINISMO de la IZQUIERDA tras el 8M',
                            'Url': 'kv7-A4zMzOM'},
                           {'Title':'¡EL CONGRESO SE DESCOJONA DE SÁNCHEZ! ABASCAL se BURLA de ÉL, le IMITA ¡Y LAS CARCAJADAS SON ÉPICAS!',
                            'Url':'hSMfML6B6_s'},
                           {'Title':'Chiqui Montero SE METE con un JOVEN de VOX por ser SOBRINO de RATO ¡¡Y ACABA BRUTALMENTE HUMILLADA!!',
                            'Url':'pT57jg8VT4o'},
                           {'Title':'"¡OS VAIS A TENER QUE TRAGAR A LOS MOROS!" | Esta MUSULMANA SE PASA DE LISTA con VOX ¡Y PASA ESTO!',
                            'Url': 'EPkxJqB24s4'},
                           {'Title':'¡AYUSO REVIENTA A LA SEXTA CON UNA FRASE LAPIDARIA MIENTRAS INTENTABAN BLANQUEAR A OTEGI Y SU BANDA!',
                            'Url':'kRjkNOOM8tA'},
                           {'Title':'Un diputado GAY del PP se HARTA de la DEMAGOGIA LGTB de PODEMOS ¡¡Y VEAN EL DESTROZO QUE LES HACE!!',
                            'Url':'ksB37A4B72c'},
                           {'Title':'El debate electoral en la Cadena SER, íntegro',
                            'Url':'RMai7UVSMgs'},
                           {'Title':'Pablo Iglesias abandona el debate de la Cadena SER tras poner Vox en duda la denuncia sobre la ca...',
                            'Url': 'TM6UyyosjA0'}]
               },
    'Ecuador': {'Reddit': ['ecuador'],
               'Twitter': ['politica ecuador', 'politica ecuatoriana'],
               'Youtube': [{'Title':'TOP 10: Momentos más vergonzosos de la política ecuatoriana',
                            'Url':'6hBOelWDA4E'},
                           {'Title':'Debate que NO FUE DEBATE | Payasadas de los CANDIDATOS | BN Periodismo | Noticias de Ecuador',
                            'Url':'Kwj8B4AyXB4'},
                           {'Title':'Guillermo LASSO y sus TROPEZONES | LAS PROMESAS INCUMPLIDAS | BN Periodismo | Noticias de Ecuador',
                            'Url': '7SQ0axOlEsU'},
                           {'Title':'Todo sobre Guillermo LASSO | La HISTORIA del BANQUERO | BN Periodismo | Noticias de Ecuador',
                            'Url':'MC9ykvJY3tw'},
                           {'Title':'AUGUSTO TANDAZO DENUNCIA : EL PROBLEMA ES LA DECLARACIÓN PATRIMONIAL DE LASSO',
                            'Url':'4LNVhH-0w40'},
                           {'Title':'"UNES EL CHANTAJE Y LA POLÍTICA DEMENCIAL EN EL ECUADOR"',
                            'Url':'O-zPjpBSnTQ'},
                           {'Title':'ANDRÉS ARÁUZ: ¡LASSO DEBE RENUNCIAR O SER DESTITUIDO! Entrevista con Francisco Herrera Aráuz',
                            'Url':'gNVN2vmsS74'},
                           {'Title':'Rafael Correa FELICITA a Guillermo Lasso por GANAR la Presidencia',
                            'Url':'BaNBdDTpBJo'}]
               }
}